name: customer-happiness-prediction
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - joblib
  - pip
  - pip:
    - lazypredict
